pub mod add_curve_dialog;
pub mod add_pair_dialog;
mod cpu_info_card;
mod curve_card;
mod curve_editor;
mod curves_page;
mod dashboard;
mod detection_dialog;
mod ec_control_page;
mod fan_pairing_page;
mod settings_page;
mod edit_curve_dialog;
mod fan_card;
mod gpu_card;
mod gpu_info_card;
mod graphs_page;
mod nav_sidebar;
mod sensors_page;
mod system_info;
mod temp_monitor;

pub use curves_page::CurvesPage;
pub use dashboard::Dashboard;
pub use detection_dialog::DetectionDialog;
pub use ec_control_page::EcControlPage;
pub use fan_pairing_page::FanPairingPage;
pub use graphs_page::GraphsPage;
pub use nav_sidebar::NavPage;
pub use sensors_page::SensorsPage;
pub use settings_page::SettingsPage;
